Interpreter
JustasGau/DonjinKrawler pull request #34
Opened 2020-12-06 12:31 UTC by lukasbernotas

Very basic console application

2020-12-06 16:32 UTC, ArvApu requested changes
Gerai padirbėta, tik yra keli smulkūs pakeitimai reikalingi.

2020-12-06 16:32 UTC, ArvApu commented on DonjinKrawler-Console/src/main/java/donjinkrawler/CommandParser.java
> +public class CommandParser {
Reiktu padaryti final. 

[CHECKLIST](https://dzone.com/articles/java-code-review-checklist):
`Make class final if not being used for inheritance.`

2020-12-06 16:32 UTC, ArvApu commented on DonjinKrawler-Console/src/main/java/donjinkrawler/Console.java
> +public class Console {
Reiktu final pridėti.

[CHECKLIST](https://dzone.com/articles/java-code-review-checklist):
`Make class final if not being used for inheritance.`

2020-12-06 16:32 UTC, ArvApu commented on DonjinKrawler-Console/src/main/java/donjinkrawler/Console.java
> +        Client client = new Client(65536, 65536);
Čia šiti skaičiukai, kad nebūtu „magical“, gal reiktu padaryti kaip konstantas.

2020-12-09 16:28 UTC, JustasGau commented
Reiktų padaryt kad veiktų su memento. Dabar ten basic input readeris yra, reaguoja į "save" ir "load" komandas, reiktų jį pašalinti

2020-12-09 16:44 UTC, ArvApu approved these changes

2020-12-09 16:45 UTC, merged